"""propor

Revision ID: 96797eb7534d
Revises: fe8483ed6745
Create Date: 2024-09-10 15:06:11.502794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96797eb7534d'
down_revision = 'fe8483ed6745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serviceName', sa.String(), nullable=True))
        batch_op.alter_column('serviceId',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'service', ['serviceName'], ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('serviceId',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.drop_column('serviceName')

    # ### end Alembic commands ###
