"""empty message

Revision ID: bb2fe16472f4
Revises: bd18765c7d69
Create Date: 2024-09-10 12:35:10.432386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb2fe16472f4'
down_revision = 'bd18765c7d69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('laugh')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('laugh', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
