"""by

Revision ID: dc1bbcaa304a
Revises: c8b52530e7f9
Create Date: 2024-09-09 16:01:24.301770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc1bbcaa304a'
down_revision = 'c8b52530e7f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('example', sa.String(), nullable=True))
        batch_op.drop_column('eample')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eample', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('example')

    # ### end Alembic commands ###
