"""pro

Revision ID: f682bc11762d
Revises: dc1bbcaa304a
Create Date: 2024-09-09 16:14:35.901944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f682bc11762d'
down_revision = 'dc1bbcaa304a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_column('example')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('example', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
